---
- name: "Check if ~/bin exists"
  stat:
    path: "~/bin"
  register: "stat_bin_result"
  tags:
    - "scripts"

- name: "Install ~/bin directory"
  ansible.builtin.file:
    path: "~/bin"
    state: directory
    mode: "0755"
  when: "not stat_bin_result.stat.exists"
  tags:
    - "scripts"

- name: "Install scripts"
  copy:
    src: "{{ item }}"
    dest: "~/bin/{{ item }}"
    mode: "0755"
  with_items:
    - "256colors.pl"
    - "ack"
    - "average"
    - "base64"
    - "cdiff"
    - "colordiff"
    - "crypt.pl"
    - "git-whoami"
    - "install_starship.sh"
    - "ipv6_ptr_dns"
    - "lwall.quote.pl"
    - "nums.pl"
    - "numsum"
    - "random"
    - "randpass"
    - "randpin"
    - "randpin5"
    - "sha.pl"
    - "ssh-chain"
    - "stat.pl"
    - "whohassocket.sh"
  tags:
    - "scripts"
