- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result
  tags:
    - zsh

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists
  tags:
    - zsh

- name: "Install zshrc"
  copy:
    src: "{{ dotfiles }}/zshrc"
    dest: "~/.zshrc"
    mode: 0644
  tags:
    - zsh
