---
- hosts: "all"
  vars_files:
    - "./vars/gituser.yml"
    - "./vars/homebrew.yml"
  roles:
    - {role: "homebrew"}
    - {role: "zsh"}
    - {role: "misc"}
    - {role: "scripts"}
    - {role: "vcs"}
    - {role: "vim"}
    - {role: "neovim"}
    - {role: "starship"}
    - {role: "fonts"}
    - {role: "doomemacs"}
