- hosts: "all"
  vars_files:
    - "./vars/gituser.yml"
  roles:
    - { role: "zsh" }
    - { role: "vcs" }
    - { role: "misc" }
    - { role: "vim" }

- hosts: "local"
  roles:
    - { role: "scripts" }

- hosts: "neovim"
  roles:
    - { role: "neovim" }

- hosts: "nvimappimg"
  roles:
    - { role: "nvimappimg" }
