- hosts: all
  vars_files:
    - "./vars/gituser.yml"
  roles:
    - { role: zsh }
    - { role: vcs }
    - { role: misc }
    - { role: vim }
    - { role: neovim }
    - { role: scripts }
    - { role: starship }

