- hosts: all
  roles:
    - { role: zsh }
    - { role: vcs }
    - { role: misc }
    - { role: gnupg }
    - { role: vim }
    - { role: scripts }

- hosts: macos
  vars_files:
    - "./vars/homebrew.yml"
  roles:
    - { role: homebrew }
    - { role: puppet }
    - { role: jupyter }
    - { role: nodebook }
