#!/usr/bin/env bash
# Like `tmux select-pane`, but if Vim or Weechat are running in the current
# pane it sends through a `<C-h/j/k/l>` keystroke instead.
# Assumes Vim/Weechat are set up to know what to do with that.

# Doesn't seem to work with Bash 3 (e.g. on OS X use homebrew 'bash')

set -e

cmd="$(tmux display -p '#{pane_current_command}')"

if [[ "${cmd,,*}" = "vim" || "${cmd,,*}" = "Vim" || "${cmd// [0-9.]*/}" = "weechat" ]]; then
    direction="$(echo "${1#-}" | tr 'lLDUR' '\\hjkl')"
    # forward the keystroke to Vim or weechat
    tmux send-keys "C-$direction"
else
    tmux select-pane "$@"
fi
