#!/usr/bin/env python3

"""
Take in an IPv6 address, return the 'ip6.arpa' long form used
in PTR DNS records.
"""

import re
import sys

if len(sys.argv) < 2:
    print("Missing argument")
    sys.exit(1)

address = sys.argv[1]

# Throw away netmask data - it's irrelevant to DNS
address = re.sub(r'/\d+$', '', address)

# Error if there is more than one occurrence of a double-colon
if re.search(r'::.*::', address):
    print("Only one pair of double-colons is allowed")
    sys.exit(1)


def pad(chunk):
    """Pad a chunk to 4 positions using leading zeroes"""
    strc = str(chunk)
    if len(strc) > 4:
        print("Broken chunk length")
        sys.exit(1)
    while len(strc) != 4:
        strc = "0" + strc
    return strc


# Put all the chunks together in an array
chunks = []

if m := re.match(r'(.*)::(.*)', address):

    # Split in two parts if there's a double colon present
    before = m.group(1)
    after = m.group(2)

    # Figure out how many chunks were before and after the double colon,
    # and how many chunks we need to fill that gap
    before_size = len(before.split(':'))
    after_size = len(after.split(':'))
    chunks_needed = 8 - (before_size + after_size)

    for c in before.split(':'):
        chunks.append(pad(c))

    while chunks_needed > 0:
        chunks.append("0000")
        chunks_needed -= 1

    for c in after.split(':'):
        chunks.append(pad(c))

else:

    # No double-colons, so we're just doing a plain split string here.
    for c in address.split(':'):
        chunks.append(pad(c))

if len(chunks) != 8:
    print("Incorrect number of address atoms (should be 8)")
    sys.exit(1)

# Join chunks, reverse the whole thing, insert dots and domain suffix.
print('.'.join(''.join(chunks).lower()[::-1]) + '.ip6.arpa.')
