#!/bin/sh

# Print a summary of what's in num-utils since I can't usually remember.

cat <<EOF
average         A program for calculating the average of numbers.
bound           Finds the boundary numbers (min and max) of input.
interval        Shows the numeric intervals between each number in a sequence.
normalize       Normalizes a set of numbers between 0 and 1 by default.
numgrep         Like normal grep, but for sets of numbers.
numprocess      Do mathmatical operations on numbers.
numsum          Add up all the numbers.
random          Generate a random number from a given expression.
range           Generate a set of numbers in a range expression.
round           Round each number according to its value.
EOF
