- name: "Create .gnupg directory"
  file:
    path: "~/.gnupg"
    state: directory
    mode: 0700
  tags:
    - gpg
    - gnupg

- name: "Install gnupg config file"
  template:
    src: gpg.conf.j2
    dest: "~/.gnupg/gpg.conf"
    mode: 0600
  tags:
    - gpg
    - gnupg
