- name: "Install hiera-eyaml gem"
  gem:
    name: hiera-eyaml
    state: present
    executable: /usr/local/bin/gem
    user_install: no
  tags:
    - puppet

- name: "Install hiera-eyaml-gpg gem"
  gem:
    name: hiera-eyaml-gpg
    state: present
    executable: /usr/local/bin/gem
    user_install: no
  tags:
    - puppet

- name: "Install gpgme gem"
  gem:
    name: gpgme
    state: present
    executable: /usr/local/bin/gem
    user_install: no
  tags:
    - puppet

- name: "Install yard gem"
  gem:
    name: yard
    state: present
    executable: /opt/puppetlabs/puppet/bin/gem
    user_install: no
  become: true
  tags:
    - puppet

- name: "Install puppet-strings gem"
  gem:
    name: puppet-strings
    state: present
    executable: /opt/puppetlabs/puppet/bin/gem
    user_install: no
  become: true
  tags:
    - puppet
