- name: "Check if .oh-my-zsh exists"
  stat:
    path: "~/.oh-my-zsh"
  register: "stat_oh_my_zsh_result"
  tags:
    - "zsh"

- name: "Cloning oh-my-zsh"
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh"
    dest: "~/.oh-my-zsh"
  when: "not stat_oh_my_zsh_result.stat.exists"
  tags:
    - "zsh"

- name: "Check if zsh-autosuggestions exists"
  stat:
    path: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  register: "stat_oh_my_zsh_autosuggestions_result"
  tags:
    - "zsh"

- name: "Cloning zsh-autosuggestions"
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  when: "not stat_oh_my_zsh_autosuggestions_result.stat.exists"
  tags:
    - "zsh"

- name: "Check if zsh-syntax-highlighting exists"
  stat:
    path: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  register: "stat_oh_my_zsh_syntax_highlighting_result"
  tags:
    - "zsh"

- name: "Cloning zsh-syntax-highlighting"
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  when: "not stat_oh_my_zsh_syntax_highlighting_result.stat.exists"
  tags:
    - "zsh"

- name: "Install .zshrc"
  copy:
    src: "zshrc"
    dest: "~/.zshrc"
    mode: "0644"
  tags:
    - "zsh"
