- name: "Install version-control files"
  copy:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
    mode: "0644"
  with_items:
    - "gitignore"
    - "cvsrc"
  tags:
    - "vcs"

- name: "Install .gitconfig" 
  template:
    src: "{{ item }}.j2"
    dest: "~/.{{ item }}"
    mode: "0644"
  with_items:
    - "gitconfig"
  tags:
    - "vcs"
