- name: "Install version-control configurations"
  template:
    src: "{{ item }}.j2"
    dest: "~/.{{ item }}"
    mode: 0644
  with_items:
    - gitconfig
    - gitignore
    - cvsrc
  tags:
    - vcs

- name: "Install git-credential-osxkeychain"
  when: ansible_os_family == "Darwin"
  copy:
    src: "git-credential-osxkeychain"
    dest: /usr/local/bin/git-credential-osxkeychain
    mode: 0755
  tags:
    - vcs
