- name: "Install homebrew packages"
  homebrew:
    update_homebrew: "yes"
    upgrade_all: "yes"
    name: "{{ homebrew_packages }}"
    state: "latest"
  notify: "Brew admin tasks"
  tags:
    - "homebrew"
