
- name: "Install homebrew packages"
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
    name: "{{ homebrew_packages }}"
    state: latest
  notify: "Brew administrative tasks"
  tags:
    - homebrew

- name: "nginx config"
  template:
    src: nginx.conf.j2
    dest: "/usr/local/etc/nginx.conf"
  notify: "Brew administrative tasks"
  tags:
    - nginx
    - homebrew
