---
- name: "Add tap for jandedobbeleer/oh-my-posh"
  community.general.homebrew_tap:
    name: "jandedobbeleer/oh-my-posh"
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - "homebrew"

- name: "Trust tap jandedobbeleer/oh-my-posh"
  ansible.builtin.shell: "brew trust jandedobbeleer/oh-my-posh"
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - "homebrew"

- name: "Install homebrew packages"
  community.general.homebrew:
    update_homebrew: "yes"
    upgrade_all: "yes"
    name: "{{ homebrew_packages }}"
    state: "latest"
  register: "brew_install_result"
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - "homebrew"

- name: "List of changed Homebrew packages"
  debug:
    var: "brew_install_result.changed_pkgs"
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - "homebrew"

- name: "Install homebrew casks"
  community.general.homebrew_cask:
    update_homebrew: "no"
    upgrade_all: "yes"
    name: "{{ homebrew_casks }}"
    state: "latest"
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - "homebrew"

- name: "Add tap for railwaycat/emacsmacport"
  community.general.homebrew_tap:
    name: "railwaycat/emacsmacport"
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - "homebrew"

- name: "Install emacs-mac --with-modules"
  community.general.homebrew:
    update_homebrew: "no"
    upgrade_all: "no"
    name: "emacs-mac"
    state: "latest"
    install_options: "formula,with-modules"
  register: "brew_install_emacs_result"
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - "homebrew"

- name: "List of changed emacs packages"
  debug:
    var: "brew_install_emacs_result.changed_pkgs"
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - "homebrew"
