- name: "Create nodebook data directory"
  file:
    owner: dan
    group: staff
    mode: 0755
    path: "{{ ansible_user_dir }}/Dropbox/Apps/nbk"
    state: directory
  tags:
    - nodejs
    - nodebook
    - nbk

- name: "Install nodebook"
  yarn:
    name: nbk
    global: yes
    production: yes
    state: latest
  tags:
    - nodejs
    - nodebook
    - nbk

- name: "Install nodebook service"
  template:
    src: com.tangledhelix.nbk.plist.j2
    dest: "{{ ansible_user_dir }}/Library/LaunchAgents/com.tangledhelix.nbk.plist"
  tags:
    - nodejs
    - nodebook
    - nbk
  notify: "Set up nodebook"
