---
- name: "Check if ~/.config/emacs exists"
  ansible.builtin.stat:
    path: "~/.config/emacs"
  register: "stat_config_emacs_result"
  tags: ["doom", "emacs", "doomemacs"]

- name: "Cloning doomemacs"
  ansible.builtin.git:
    repo: "https://github.com/doomemacs/doomemacs"
    dest: "~/.config/emacs"
    depth: 1
  when: "not stat_config_emacs_result.stat.exists"
  tags: ["doom", "emacs", "doomemacs"]

- name: "Check if ~/.config/doom exists"
  ansible.builtin.stat:
    path: "~/.config/doom"
  register: "stat_config_doom_result"
  tags: ["doom", "emacs", "doomemacs"]

# only when ~/.config/doom did not exist
- name: "Installing doomemacs"
  ansible.builtin.shell: "~/.config/emacs/bin/doom install --no-env --no-color"
  when: "not stat_config_doom_result.stat.exists"
  tags: ["doom", "emacs", "doomemacs"]

# only when ~/.config/doom existed
- name: "Upgrading doomemacs"
  ansible.builtin.shell: "~/.config/emacs/bin/doom upgrade --force --no-color"
  when: "stat_config_doom_result.stat.exists"
  tags: ["doom", "emacs", "doomemacs"]

- name: "Install doomemacs config.el"
  copy:
    src: "config.el"
    dest: "~/.config/doom/config.el"
    mode: "0644"
  tags: ["doom", "emacs", "doomemacs"]

- name: "Install doomemacs init.el"
  copy:
    src: "init.el"
    dest: "~/.config/doom/init.el"
    mode: "0644"
  notify: "Run doom sync"
  tags: ["doom", "emacs", "doomemacs"]

- name: "Install doomemacs packages.el"
  copy:
    src: "packages.el"
    dest: "~/.config/doom/packages.el"
    mode: "0644"
  notify: "Run doom sync"
  tags: ["doom", "emacs", "doomemacs"]
