- name: "Check if ~/bin/ exists"
  ansible.builtin.stat:
    path: "~/bin"
  register: "stat_bindir_result"
  tags:
    - "nvimappimg"

- name: "Install ~/bin directory"
  ansible.builtin.file:
    path: "~/bin"
    state: directory
    mode: "0755"
  when: "not stat_bindir_result.stat.exists"
  tags:
    - "nvimappimg"

- name: "Check if ~/bin/nvim.appimage exists"
  ansible.builtin.stat:
    path: "~/bin/nvim.appimage"
  register: "stat_nvimappimg_result"
  tags:
    - "nvimappimg"

- name: "Installing Neovim appimage"
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: "~/bin/nvim.appimage"
    mode: "0755"
  when: "not stat_nvimappimg_result.stat.exists"
  tags:
    - "nvimappimg"

