#!/usr/bin/env ruby

def usage
  puts 'Usage: wwf <includes> [ <excludes> ]'
  puts 'Example: wwf gvd yomn'
  puts 'Meaning: Words with [ g, v, d ] but without [ y, o, m, n ]'
  exit
end

ARGV[0] ? inclChars = ARGV[0].split('') : usage()
ARGV[1] ? exclChars = ARGV[1].split('') : exclChars = []

# TODO: Should we omit downcase? Arguably yes, because proper nouns
# are not normally allowed in Scrabble-like games.

File.foreach('/usr/share/dict/words') do |line|
  skip = false
  inclChars.each { |char| skip = true unless line.downcase.index(char) }
  exclChars.each { |char| skip = true if line.downcase.index(char) }
  puts line unless skip
end

