- name: "Install misc files"
  template:
    src: "{{ item }}.j2"
    dest: "~/.{{ item }}"
    mode: 0644
  with_items:
    - colordiffrc
    - emacs
    - inputrc
    - perldb
    - perltidyrc
    - pgclirc
    - psqlrc
    - screenrc
    - tcshrc
    - tmux.conf
  tags:
    - misc
