- name: "Install misc files"
  copy:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
    mode: "0644"
  with_items:
    - "colordiffrc"
    - "emacs"
    - "inputrc"
    - "perldb"
    - "perltidyrc"
    - "psqlrc"
    - "screenrc"
    - "tcshrc"
    - "tmux.conf"
  tags:
    - "misc"
