- name: "Create directory structure"
  file:
    path: "{{ item }}"
    state: "directory"
    mode: "0755"
  with_items:
    - "~/.config"
    - "~/.config/nvim"
    - "~/.config/nvim/lua"
    - "~/.config/nvim/after"
    - "~/.config/nvim/after/plugin"
  tags:
    - "neovim"

- name: "Check whether packer is installed"
  stat:
    path: "~/.local/share/nvim/site/pack/packer/start/packer.nvim"
  register: "stat_packer_result"
  tags:
    - "neovim"

- name: "Clone packer"
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "~/.local/share/nvim/site/pack/packer/start/packer.nvim"
  when: "not stat_packer_result.stat.exists"
  tags:
    - "neovim"

- name: "Install neovim config files"
  copy:
    src: "{{ item }}.lua"
    dest: "~/.config/nvim/{{ item }}.lua"
    mode: "0644"
  with_items:
    - "init"
    - "lua/filetype"
    - "lua/plugins"
    - "lua/remap"
    - "lua/set"
    - "lua/autocmd"
    - "lua/autoformat"
    - "after/plugin/autopairs"
    - "after/plugin/colors"
    - "after/plugin/comment"
    - "after/plugin/fterm"
    - "after/plugin/gitsigns"
    - "after/plugin/harpoon"
    - "after/plugin/lazygit"
    - "after/plugin/lsp"
    - "after/plugin/lualine"
    - "after/plugin/surround"
    - "after/plugin/telescope"
    - "after/plugin/todocomments"
    - "after/plugin/treesitter"
    - "after/plugin/undotree"
  tags:
    - "neovim"

