- name: "Create ~/.config/"
  file:
    path: "~/.config"
    state: "directory"
    mode: "0755"
  tags:
    - "neovim"

- name: "Create ~/.config/nvim/"
  file:
    path: "~/.config/nvim"
    state: "directory"
    mode: "0755"
  tags:
    - "neovim"

- name: "Create ~/.config/nvim/lua/"
  file:
    path: "~/.config/nvim/lua"
    state: "directory"
    mode: "0755"
  tags:
    - "neovim"

- name: "Create ~/.config/nvim/after/"
  file:
    path: "~/.config/nvim/after"
    state: "directory"
    mode: "0755"
  tags:
    - "neovim"

- name: "Create ~/.config/nvim/after/plugin/"
  file:
    path: "~/.config/nvim/after/plugin"
    state: "directory"
    mode: "0755"
  tags:
    - "neovim"

- name: "Check whether packer is installed"
  stat:
    path: "~/.local/share/nvim/site/pack/packer/start/packer.nvim"
  register: "stat_packer_result"
  tags:
    - "neovim"

- name: "Clone packer"
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "~/.local/share/nvim/site/pack/packer/start/packer.nvim"
  when: "not stat_packer_result.stat.exists"
  tags:
    - "neovim"

- name: "Install neovim init file"
  template:
    src: "init.lua.j2"
    dest: "~/.config/nvim/init.lua"
    mode: "0644"
  tags:
    - "neovim"

- name: "Install neovim set.lua"
  template:
    src: "lua/set.lua.j2"
    dest: "~/.config/nvim/lua/set.lua"
    mode: "0644"
  tags:
    - "neovim"

- name: "Install neovim remap.lua"
  template:
    src: "lua/remap.lua.j2"
    dest: "~/.config/nvim/lua/remap.lua"
    mode: "0644"
  tags:
    - "neovim"

- name: "Install neovim plugins.lua"
  template:
    src: "lua/plugins.lua.j2"
    dest: "~/.config/nvim/lua/plugins.lua"
    mode: "0644"
  tags:
    - "neovim"

- name: "Install after/plugin/telescope"
  template:
    src: "after/plugin/telescope.lua.j2"
    dest: "~/.config/nvim/after/plugin/telescope.lua"
    mode: "0644"
  tags:
    - "neovim"

- name: "Install after/plugin/harpoon"
  template:
    src: "after/plugin/harpoon.lua.j2"
    dest: "~/.config/nvim/after/plugin/harpoon.lua"
    mode: "0644"
  tags:
    - "neovim"

- name: "Install after/plugin/todocomments"
  template:
    src: "after/plugin/todocomments.lua.j2"
    dest: "~/.config/nvim/after/plugin/todocomments.lua"
    mode: "0644"
  tags:
    - "neovim"

- name: "Install after/plugin/undotree"
  template:
    src: "after/plugin/undotree.lua.j2"
    dest: "~/.config/nvim/after/plugin/undotree.lua"
    mode: "0644"
  tags:
    - "neovim"

- name: "Install after/plugin/treesitter"
  template:
    src: "after/plugin/treesitter.lua.j2"
    dest: "~/.config/nvim/after/plugin/treesitter.lua"
    mode: "0644"
  tags:
    - "neovim"

- name: "Install after/plugin/lsp"
  template:
    src: "after/plugin/lsp.lua.j2"
    dest: "~/.config/nvim/after/plugin/lsp.lua"
    mode: "0644"
  tags:
    - "neovim"
